// copy and rename to authkey.js, the details are provided in discord notes
const REACT_APP_FIREBASE_API_KEY="AIzaSyCksejRRjPuMGnyBNuPIFCjn07SgQBabdA";
const REACT_APP_FIREBASE_AUTH_DOMAIN="blueocean-4d75b.firebaseapp.com";
const REACT_APP_FIREBASE_PROJECT_ID="blueocean-4d75b";
const REACT_APP_FIREBASE_STORAGE_BUCKET="blueocean-4d75b.appspot.com";
const REACT_APP_FIREBASE_MESSAGING_SENDER_ID="83545570022";
const REACT_APP_FIREBASE_APP_ID="1:83545570022:web:03fc661cf9d8822b399927";

module.exports = {
  REACT_APP_FIREBASE_API_KEY,
  REACT_APP_FIREBASE_AUTH_DOMAIN,
  REACT_APP_FIREBASE_PROJECT_ID,
  REACT_APP_FIREBASE_STORAGE_BUCKET,
  REACT_APP_FIREBASE_MESSAGING_SENDER_ID,
  REACT_APP_FIREBASE_APP_ID
}
